version: '3'
services:
  app:
    restart: always
    container_name: telemedicine_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - intern

  db:
    image: postgres:12
    container_name: telemedicine_db
    env_file:
      - ./server/.env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - '$TELEMEDICINE_DATA:/var/lib/postgresql/data'
    networks:
      - intern

networks:
  intern:
    driver: bridge